<div class="mx-auto max-w-6xl space-y-5">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div><h1 class="text-2xl font-black tracking-tight text-slate-800">Promociones</h1><p class="text-xs font-medium text-slate-500">Descuentos por producto y vigencia.</p></div>
        <div class="flex gap-2"><input wire:model.live="search" type="search" placeholder="Buscar..." class="rounded-xl border-slate-200 px-3 py-2 text-sm"><button wire:click="create" class="rounded-xl bg-orange-600 px-4 py-2 text-xs font-black uppercase text-white hover:bg-orange-700">Nueva</button></div>
    </div>
    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <table class="w-full text-left text-sm"><thead class="bg-slate-50 text-[10px] font-black uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-4">Promoción</th><th class="px-5 py-4">Producto</th><th class="px-5 py-4">Descuento</th><th class="px-5 py-4">Vigencia</th><th class="px-5 py-4 text-right">Acciones</th></tr></thead>
            <tbody class="divide-y divide-slate-100">@forelse ($promotions as $promotion)<tr><td class="px-5 py-4 font-bold text-slate-700">{{ $promotion->name }}</td><td class="px-5 py-4 text-slate-600">{{ $promotion->product->name }}</td><td class="px-5 py-4 font-black text-emerald-600">{{ $promotion->discount_type === 'percent' ? rtrim(rtrim($promotion->value, '0'), '.') . '%' : $empresa->currency_simbol . number_format($promotion->value, 2) }}</td><td class="px-5 py-4 text-xs text-slate-500">{{ $promotion->starts_at?->format('d/m H:i') ?? 'Ahora' }} - {{ $promotion->ends_at?->format('d/m H:i') ?? 'Sin fin' }}</td><td class="px-5 py-4"><div class="flex justify-end gap-2"><button wire:click="edit({{ $promotion->id }})" class="w-9 h-9 flex items-center justify-center rounded-xl bg-white text-slate-400 hover:text-amber-600 hover:border-amber-200 transition-all border border-slate-200 shadow-sm"><i class="fa-solid fa-pen text-[10px]"></i></button><button wire:click="deleteConfirm({{ $promotion->id }})" class="w-9 h-9 flex items-center justify-center rounded-xl bg-white text-slate-400 hover:text-rose-600 hover:border-rose-200 transition-all border border-slate-200 shadow-sm"><i class="fa-solid fa-trash-can text-[10px]"></i></button></div></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-sm text-slate-400">No hay promociones.</td></tr>@endforelse</tbody>
        </table><div class="border-t border-slate-100 px-5 py-3">{{ $promotions->links() }}</div>
    </div>
    @if ($isOpen)
        <div class="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/60 p-4"><form wire:submit="store" class="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div class="mb-5 flex items-center justify-between"><h2 class="text-lg font-black text-slate-800">{{ $promotion_id ? 'Editar promoción' : 'Nueva promoción' }}</h2><button type="button" wire:click="closeModal" class="text-slate-400"><i class="fa-solid fa-xmark"></i></button></div><div class="space-y-4"><div><label class="text-xs font-bold text-slate-500">Producto</label><select wire:model="product_id" class="mt-1 w-full rounded-xl border-slate-200 px-3 py-2 text-sm"><option value="">Seleccionar...</option>@foreach ($products as $product)<option value="{{ $product->id }}">{{ $product->name }} ({{ $empresa->currency_simbol }}{{ number_format($product->price, 2) }})</option>@endforeach</select><x-input-error :messages="$errors->get('product_id')" class="mt-1" /></div><div><label class="text-xs font-bold text-slate-500">Nombre</label><input wire:model="name" class="mt-1 w-full rounded-xl border-slate-200 px-3 py-2 text-sm"><x-input-error :messages="$errors->get('name')" class="mt-1" /></div><div class="grid grid-cols-2 gap-3"><div><label class="text-xs font-bold text-slate-500">Tipo</label><select wire:model="discount_type" class="mt-1 w-full rounded-xl border-slate-200 px-3 py-2 text-sm">@foreach ($discountTypes as $type)<option value="{{ $type }}">{{ $type === 'percent' ? 'Porcentaje' : 'Monto fijo' }}</option>@endforeach</select></div><div><label class="text-xs font-bold text-slate-500">Valor</label><input wire:model="value" type="number" min="0.01" step="0.01" class="mt-1 w-full rounded-xl border-slate-200 px-3 py-2 text-sm"></div></div><div class="grid grid-cols-2 gap-3"><div><label class="text-xs font-bold text-slate-500">Inicia</label><input wire:model="starts_at" type="datetime-local" class="mt-1 w-full rounded-xl border-slate-200 px-3 py-2 text-sm"></div><div><label class="text-xs font-bold text-slate-500">Termina</label><input wire:model="ends_at" type="datetime-local" class="mt-1 w-full rounded-xl border-slate-200 px-3 py-2 text-sm"></div></div><label class="flex items-center gap-2 text-xs font-bold text-slate-600"><input wire:model="active" type="checkbox" class="rounded border-slate-300 text-orange-600"> Activa</label><x-input-error :messages="$errors->get('value')" /><x-input-error :messages="$errors->get('ends_at')" /><button class="w-full rounded-xl bg-orange-600 py-3 text-xs font-black uppercase text-white hover:bg-orange-700">Guardar</button></div></form></div>
    @endif
</div>
